/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	v1beta "github.com/attsun1031/k8s-crd-sample/pkg/apis/workflow/v1beta"
	"github.com/attsun1031/k8s-crd-sample/pkg/client/clientset/versioned/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type WorkflowV1betaInterface interface {
	RESTClient() rest.Interface
	WorkflowsGetter
}

// WorkflowV1betaClient is used to interact with features provided by the workflow.com group.
type WorkflowV1betaClient struct {
	restClient rest.Interface
}

func (c *WorkflowV1betaClient) Workflows(namespace string) WorkflowInterface {
	return newWorkflows(c, namespace)
}

// NewForConfig creates a new WorkflowV1betaClient for the given config.
func NewForConfig(c *rest.Config) (*WorkflowV1betaClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &WorkflowV1betaClient{client}, nil
}

// NewForConfigOrDie creates a new WorkflowV1betaClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *WorkflowV1betaClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new WorkflowV1betaClient for the given RESTClient.
func New(c rest.Interface) *WorkflowV1betaClient {
	return &WorkflowV1betaClient{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1beta.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *WorkflowV1betaClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
